/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_sju_ee_ni_daqmx_TaskHandle */

#ifndef _Included_edu_sju_ee_ni_daqmx_TaskHandle
#define _Included_edu_sju_ee_ni_daqmx_TaskHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_sju_ee_ni_daqmx_TaskHandle
 * Method:    nTaskHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_sju_ee_ni_daqmx_TaskHandle_nTaskHandle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_sju_ee_ni_daqmx_TaskHandle
 * Method:    nfinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_TaskHandle_nfinalize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     edu_sju_ee_ni_daqmx_TaskHandle
 * Method:    test
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_TaskHandle_test
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
