/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_sju_ee_ni_daqmx_DAQmx */

#ifndef _Included_edu_sju_ee_ni_daqmx_DAQmx
#define _Included_edu_sju_ee_ni_daqmx_DAQmx
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_Acquired_Into_Buffer
#define edu_sju_ee_ni_daqmx_DAQmx_Val_Acquired_Into_Buffer 1L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_Transferred_From_Buffer
#define edu_sju_ee_ni_daqmx_DAQmx_Val_Transferred_From_Buffer 2L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_GroupByChannel
#define edu_sju_ee_ni_daqmx_DAQmx_Val_GroupByChannel 0L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_GroupByScanNumber
#define edu_sju_ee_ni_daqmx_DAQmx_Val_GroupByScanNumber 1L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_Cfg_Default
#define edu_sju_ee_ni_daqmx_DAQmx_Val_Cfg_Default -1L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_Volts
#define edu_sju_ee_ni_daqmx_DAQmx_Val_Volts 10348L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_FiniteSamps
#define edu_sju_ee_ni_daqmx_DAQmx_Val_FiniteSamps 10178L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_ContSamps
#define edu_sju_ee_ni_daqmx_DAQmx_Val_ContSamps 10123L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_HWTimedSinglePoint
#define edu_sju_ee_ni_daqmx_DAQmx_Val_HWTimedSinglePoint 12522L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_Rising
#define edu_sju_ee_ni_daqmx_DAQmx_Val_Rising 10280L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_Falling
#define edu_sju_ee_ni_daqmx_DAQmx_Val_Falling 10171L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_CSeriesModule
#define edu_sju_ee_ni_daqmx_DAQmx_Val_CSeriesModule 14659L
#undef edu_sju_ee_ni_daqmx_DAQmx_Val_SCXIModule
#define edu_sju_ee_ni_daqmx_DAQmx_Val_SCXIModule 14660L
/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_construct
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_destruct
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    isAlive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_isAlive
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    createTask
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_createTask
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    startTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_startTask
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    stopTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_stopTask
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    clearTask
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_clearTask
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    getNthTaskDevice
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_getNthTaskDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    registerEveryNSamplesEvent
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_registerEveryNSamplesEvent
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    registerDoneEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_registerDoneEvent
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    createAIVoltageChan
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_createAIVoltageChan
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jint, jstring);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    createAOVoltageChan
 * Signature: (Ljava/lang/String;Ljava/lang/String;DDILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_createAOVoltageChan
  (JNIEnv *, jobject, jstring, jstring, jdouble, jdouble, jint, jstring);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    cfgDigEdgeStartTrig
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_cfgDigEdgeStartTrig
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    readAnalogF64
 * Signature: (IDZ[DILjava/lang/Boolean;)I
 */
JNIEXPORT jint JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_readAnalogF64
  (JNIEnv *, jobject, jint, jdouble, jboolean, jdoubleArray, jint, jobject);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    writeAnalogF64
 * Signature: (IZDZ[D)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_writeAnalogF64
  (JNIEnv *, jobject, jint, jboolean, jdouble, jboolean, jdoubleArray);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    getDevProductCategory
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_getDevProductCategory
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    getTaskNumDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_getTaskNumDevices
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    cfgSampClkTiming
 * Signature: (Ljava/lang/String;DIIJ)V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_cfgSampClkTiming
  (JNIEnv *, jobject, jstring, jdouble, jint, jint, jlong);

/*
 * Class:     edu_sju_ee_ni_daqmx_DAQmx
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee_ni_daqmx_DAQmx_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
