/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_sju_ee98_ni_daqmx_analog_AcqIntClk */

#ifndef _Included_edu_sju_ee98_ni_daqmx_analog_AcqIntClk
#define _Included_edu_sju_ee98_ni_daqmx_analog_AcqIntClk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_sju_ee98_ni_daqmx_analog_AcqIntClk
 * Method:    acqIntClk
 * Signature: (Ljava/lang/String;DDDJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_sju_ee98_ni_daqmx_analog_AcqIntClk_acqIntClk
  (JNIEnv *, jobject, jstring, jdouble, jdouble, jdouble, jlong);

#ifdef __cplusplus
}
#endif
#endif
