/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_sju_ee98_ni_daqmx_DAQmx */

#ifndef _Included_edu_sju_ee98_ni_daqmx_DAQmx
#define _Included_edu_sju_ee98_ni_daqmx_DAQmx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_sju_ee98_ni_daqmx_DAQmx
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee98_ni_daqmx_DAQmx_print
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee98_ni_daqmx_DAQmx
 * Method:    acqIntClk
 * Signature: (Ljava/lang/String;DDDJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_edu_sju_ee98_ni_daqmx_DAQmx_acqIntClk
  (JNIEnv *, jobject, jstring, jdouble, jdouble, jdouble, jlong);

#ifdef __cplusplus
}
#endif
#endif
