/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_sju_ee98_ni_daqmx_analog_ContGenIntClk */

#ifndef _Included_edu_sju_ee98_ni_daqmx_analog_ContGenIntClk
#define _Included_edu_sju_ee98_ni_daqmx_analog_ContGenIntClk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_sju_ee98_ni_daqmx_analog_ContGenIntClk
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee98_ni_daqmx_analog_ContGenIntClk_construct
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee98_ni_daqmx_analog_ContGenIntClk
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee98_ni_daqmx_analog_ContGenIntClk_destruct
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee98_ni_daqmx_analog_ContGenIntClk
 * Method:    contGenIntClk
 * Signature: (Ljava/lang/String;DDDJ[D)I
 */
JNIEXPORT jint JNICALL Java_edu_sju_ee98_ni_daqmx_analog_ContGenIntClk_contGenIntClk
  (JNIEnv *, jobject, jstring, jdouble, jdouble, jdouble, jlong, jdoubleArray);

/*
 * Class:     edu_sju_ee98_ni_daqmx_analog_ContGenIntClk
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee98_ni_daqmx_analog_ContGenIntClk_start
  (JNIEnv *, jobject);

/*
 * Class:     edu_sju_ee98_ni_daqmx_analog_ContGenIntClk
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_sju_ee98_ni_daqmx_analog_ContGenIntClk_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
